name             "vagrant_main"
maintainer       "Sergey Storchay"
maintainer_email "r8@r8.com.ua"
license          "MIT"
description      "Configures vagrant virtual machine"
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          "0.0.1"

depends          "apt"
depends          "build-essential"
depends          "git"
depends          "oh-my-zsh"
depends          "apache2"
depends          "mysql"
depends          "percona"
depends          "php"
depends          "composer"
depends          "phing"
depends          "php-box"
