name             "vagrant_main"
maintainer       "Sergey Storchay"
maintainer_email "r8@r8.com.ua"
license          "MIT"
description      "Configures vagrant virtual machine"
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          "0.0.1"

depends          "apache2"
depends          "apt"
depends          "build-essential"
depends          "composer"
depends          "git"
depends          "magento-toolbox"
depends          "mailhog"
depends          "mysql"
depends          "nodejs"
depends          "percona"
depends          "phing"
depends          "php"
depends          "poise-python"
depends          "postfix"
depends          "redisio"
