driver_plugin: vagrant
driver_config:
  require_chef_omnibus: true

platforms:
  - name: ubuntu-12.04
    run_list:
      - recipe[fake::prep]
  - name: centos-6.5

suites:
  - name: default
    run_list:
      - recipe[logrotate::default]
  - name: definition
    run_list:
      - recipe[fake::definition]
  - name: global
    run_list:
      - recipe[logrotate::global]
